name: Run Python Script

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 15 * * *'  # Runs every day at 9 AM UTC (15:00 UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas numpy openpyxl

    - name: Run Python script
      run: Skyline reports cleanup and merge_source_update_bi-weekly.py
